version: '3.8'

services:

  ai_chat:
    # image: ghcr.io/irinalepekhina/ai_chat:dev
    build:
      context: ../ai_chat
      # dockerfile: ./Dockerfile.prod
    container_name: ai_chat
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ../ai_chat:/usr/src/app
    env_file:
      - ../ai_chat/env/development/database
      - ../ai_chat/env/development/ai_chat
    depends_on: 
      ai_chat_db:
        condition: service_started
      ai_chat_redis:
        condition: service_started
    networks:
      - back
      - front

  ai_chat_redis:
    image: redis/redis-stack:latest
    container_name: ai_chat_redis
    ports:
      - "6379:6379"
    networks:
      - back

  ai_chat_redis_uploader:
    # image: ghcr.io/irinalepekhina/ai_chat:dev
    image: infrastructure-ai_chat 
    container_name: ai_chat_redis_uploader
    command: ["./wait-for", "--timeout=60", "ai_chat_redis:6379", "--",
      "ruby", "bin/redis_uploader.rb"]
    env_file:
      - ../ai_chat/env/development/database
      - ../ai_chat/env/development/ai_chat
    networks:
      - back
    deploy:
      restart_policy:
        condition: none

  ai_chat_db_migrator:
    # image: ghcr.io/irinalepekhina/ai_chat:dev
    image: infrastructure-ai_chat 
    container_name: ai_chat_db_migrator
    command: ["./wait-for", "--timeout=60", "ai_chat_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - ../ai_chat/env/development/database
      - ../ai_chat/env/development/ai_chat
    networks:
      - back
    deploy:
      restart_policy:
        condition: none

  ai_chat_db:
    image: postgres
    container_name: ai_chat_db
    env_file:
      - ../ai_chat/env/development/database
    volumes:
      - db_data_ai_chat:/var/lib/postgresql/data
    networks:
      - back

  ai_chat_redisinsight:
    image: redislabs/redisinsight:latest
    container_name:  ai_chat_redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data_ai_chat:/db
    networks:
      - back

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    container_name:  selenium_chrome
    logging:
      driver: none
    ports:
      - "5900:5900"
    networks:
      - back

## tg_bot services
  tg_bot:
    # image: ghcr.io/irinalepekhina/tg_bot:dev
    build:
      context: ../tg_bot
      # dockerfile: ./Dockerfile.prod
    container_name: tg_bot
    ports:
      - "3001:3000"
    volumes:
      - ../tg_bot:/usr/src/app
    env_file:
      - ../tg_bot/env/development/database
      - ../tg_bot/env/development/tg_bot
    depends_on:
      tg_bot_redis:
        condition: service_started
      ai_chat:
        condition: service_started
      ngrok:
        condition: service_started
    networks:
      - front

  tg_bot_redis:
    image: redis/redis-stack:latest
    container_name: tg_bot_redis
    ports:
      - "6380:6379"
    networks:
      - front

  tg_bot_db:
    image: postgres
    container_name: tg_bot_db
    env_file:
      - ../tg_bot/env/development/database
    volumes:
      - db_data_tg_bot:/var/lib/postgresql/data
    networks:
      - front

  tg_bot_db_migrator:
    # image: ghcr.io/irinalepekhina/tg_bot:dev
    image: infrastructure-tg_bot
    container_name:  tg_bot_db_migrator
    command: ["./wait-for", "--timeout=60", "tg_bot_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - ../tg_bot/env/development/database
      - ../tg_bot/env/development/tg_bot
    networks:
      - front
    deploy:
      restart_policy:
        condition: none

  tg_bot_webhook:
    # image: ghcr.io/irinalepekhina/tg_bot:dev
    image: infrastructure-tg_bot
    container_name:  tg_bot_webhook
    env_file:
      - ../tg_bot/env/development/database
      - ../tg_bot/env/development/tg_bot
    command: ["./wait-for", "--timeout=90", "tg_bot:3000", "--",
      "ruby", "bin/set_telegram_webhook.rb"]
    networks:
      - front
    deploy:
      restart_policy:
        condition: none
        
  signup:
    # image: ghcr.io/irinalepekhina/tg_bot:dev
    image: infrastructure-tg_bot
    container_name:  signup
    command: ["./wait-for", "--timeout=120", "tg_bot:3000", "--",
      "ruby", "bin/initializing_bot_user.rb"]
    env_file:
      - ../tg_bot/env/development/database
      - ../tg_bot/env/development/tg_bot
    networks:
      - front
    deploy:
      restart_policy:
        condition: none

  ngrok:
    image: ngrok/ngrok
    container_name:  ngrok
    env_file:
      - ../tg_bot/env/development/tg_bot
    command: 
      - http
      - "tg_bot:3000"
      - "--domain=sweet-vital-coral.ngrok-free.app"
    ports:
      - "4040:4040"
    networks:
      - front

  tg_bot_redisinsight:
    image: redislabs/redisinsight:latest
    container_name:  tg_bot_redisinsight
    ports:
      - '8002:8001'
    volumes:
      - redisinsight_data_tg_bot:/db
    networks:
      - front

volumes:
  db_data_ai_chat:
  redisinsight_data_ai_chat:
  db_data_tg_bot:
  redisinsight_data_tg_bot:

networks:
  front:
    driver: bridge
  back:
    driver: bridge