version: '3.8'

services:
  web:
    image: ghcr.io/irinalepekhina/planta_chat:latest
    ports:
      - "3000:3000"
    env_file:
      - ./planta_chat/env/production/database
      - ./planta_chat/env/production/web
    networks:
      - back
      - web_tg
      - proxy_main
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.muul_web.rule=Host(`web2.muul.ru`)"
        - "traefik.http.routers.muul_web.service=muul_web"
        - "traefik.http.routers.muul_web.tls.certresolver=le"
        - "traefik.http.routers.muul_web.entrypoints=websecure,web"
        - "traefik.http.services.muul_web.loadbalancer.server.port=3000"
        - "traefik.http.services.muul_web.loadbalancer.passhostheader=true"
        # - "traefik.http.services.muul_web.loadBalancer.sticky.cookie=true"
        # - "traefik.http.services.muul_web.loadBalancer.sticky.cookie.name=_chat_session"

  web_redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    networks:
      - back
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  web_db:
    image: postgres:latest
    env_file:
      - ./planta_chat/env/production/database
    volumes:
      - db_data_web:/var/lib/postgresql/data
    networks:
      - back
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  web_db_migrator:
    image: ghcr.io/irinalepekhina/planta_chat:latest
    command: ["./wait-for", "--timeout=500", "web_db:5432", "--",
      "bin/rails",  "db:migrate", "--trace"]
    env_file:
      - ./planta_chat/env/production/database
      - ./planta_chat/env/production/web
    networks:
      - back
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  web_redis_uploader:
    image: ghcr.io/irinalepekhina/planta_chat:latest
    command: ["./wait-for", "--timeout=500", "web_redis:6379", "--",
      "ruby", "bin/redis_uploader.rb"]
    env_file:
      - ./planta_chat/env/production/database
      - ./planta_chat/env/production/web
    networks:
      - back
    deploy:
      replicas: 1
      restart_policy:
        condition: none

networks:
  back:
    driver: overlay
    attachable: true
    name: muul_back
  web_tg:
    driver: overlay
    attachable: true
    name: muul_web_tg
  proxy_main:
    external: true

volumes:
  db_data_web: